### ISSUE TITLE
Python API

### ISSUE THREAD

**Issue by mmghahremanpour** [MolSSI/qikpropservice#1]
Hi, I first thank you for this work. I would suggest to have a Python API such that a user can submit multiple compounds to the server automatically. For virtually screening out many compounds, it will be hard to submit one compound at a time. However, people can compile QikProp on their local computer. If the purpose of this sever is to help combat COVID-19, an API will be helpful.

**Comment by Lnaden** [comment]
That's a good idea. We're planning on adding that feature, but we wanted to make sure we got it working from a technical side first.

While that is in the works, the program will accept an input file with multiple molecules in a single file, so you can process multiple molecules at once.

**Comment by mmghahremanpour** [comment]
That is great that you are planning on adding that feature. 
It would also be helpful if you wrote on the web server' page that it accepts an input file with multiple molecules. Also that all submitted molecules must be neutral with all hydrogens as it has been pointed out by Bill on Twitter.

**Comment by mmghahremanpour** [comment]
That is great that you are planning on adding that feature. 
It would also be helpful if you wrote on the web server' page that it accepts an input file with multiple molecules. Also that all submitted molecules must be neutral with all hydrogens as it has been pointed out by Bill on Twitter.

**Comment by mmghahremanpour** [comment]
That is great that you are planning on adding that feature. 
It would also be helpful if you wrote on the web server' page that it accepts an input file with multiple molecules. Also that all submitted molecules must be neutral with all hydrogens as it has been pointed out by Bill on Twitter.

**Comment by mmghahremanpour** [comment]
That is great that you are planning on adding that feature. 
It would also be helpful if you wrote on the web server' page that it accepts an input file with multiple molecules. Also that all submitted molecules must be neutral with all hydrogens as it has been pointed out by Bill on Twitter.

**Comment by mmghahremanpour** [comment]
That is great that you are planning on adding that feature. 
It would also be helpful if you wrote on the web server' page that it accepts an input file with multiple molecules. Also that all submitted molecules must be neutral with all hydrogens as it has been pointed out by Bill on Twitter.

**Comment by mmghahremanpour** [comment]
That is great that you are planning on adding that feature. 
It would also be helpful if you wrote on the web server' page that it accepts an input file with multiple molecules. Also that all submitted molecules must be neutral with all hydrogens as it has been pointed out by Bill on Twitter.
